### PR TITLE
NYT article page project completed

### PR DESCRIPTION
**Pull request by MrSayyod**
[Live Link To The Website](https://rawcdn.githack.com/MrSayyod/NYT-clone/05f1706ee0b8bec203d3a40f215ec73e3b601743/index.html)

Aside: This tag is used for sidebar.
Float, Flex and Grid: All of these position attributes are used at least one time in our project.
We used article tags to form a specific line for all the paragraphs. And to form the recommended section with bottom links we used UL tag with Grid and Flex positions.

Thank you for your time and efforts...

### CODE REVIEW

**Comment by SofiBretz** [comment]
Code under review by SofiBretz. Thanks!✨

**Comment by kblycaglayan** [comment]
[Live Link To The Website](https://rawcdn.githack.com/MrSayyod/NYT-clone/da157f409ca262bb174f31cc7478d1815c518e9c/index.html)

Aside: This tag is used for sidebar.
Float, Flex and Grid: All of these position attributes are used at least one time in our project.

Thank you for your time and efforts...

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project! The design is almost exactly the same as the original page. Good Job!! 👏 You need to fix the issues below before moving on ⬇️

- [x] It’s better to delete commented code on your CSS file.  [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) you can see the information about this.
COMMENTLINE

- [x] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

- [x] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

- [x] On the 'More in Space and Astronomy' section, It contains links to other articles.

- [x] Consider positioned the link as the original page:





- [x] Consider change this, has to be as the original page:



[OPTIONAL]

- [x] Consider adding a screenshot of your project in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by kubilaycaglayan** [comment]
[Live Link](https://rawcdn.githack.com/MrSayyod/NYT-clone/05f1706ee0b8bec203d3a40f215ec73e3b601743/index.html)

**Inline comments** deleted.
**Pull Request title and description** added.
**The NY Times logo** is turned to a link.
On the 'More in Space and Astronomy' section, It **contains links added to other articles.**
**Repositioned** the bottom-link as the original page.

_Thanks for your time and information..._

**Review by nikasulo — APPROVED** [review]
# Congratulations!  @MrSayyod and @kblycaglayan 
You may merge and keep moving forward! :1st_place_medal:

**Pull request merged**
